Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

   # for provisioning common configurations
  def configure_vm(vm, ip_address, memory)
      vm.vm.box = "eurolinux-vagrant/centos-stream-9"
      vm.vm.hostname = vm.name
      vm.vm.network "private_network", ip: ip_address
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = memory
      end
      vm.vm.provision "shell", path: "common-provision.sh"
    end

  # DB VM configuration
  config.vm.define "db01" do |db01|
    configure_vm(db01, "192.168.56.15", "600")
    db01.vm.provision "shell", path: "mysql.sh"
  end

  # Memcache VM configuration
  config.vm.define "mc01" do |mc01|
    configure_vm(mc01, "192.168.56.14", "600")
    mc01.vm.provision "shell", path: "memcache.sh"
  end

  # RabbitMQ VM configuration
  config.vm.define "rmq01" do |rmq01|
    configure_vm(rmq01, "192.168.56.16", "600")
    rmq01.vm.provision "shell", path: "rabbitmq.sh"
  end

  # Tomcat VM configuration
  config.vm.define "app01" do |app01|
    configure_vm(app01, "192.168.56.12", "800")
    app01.vm.provision "shell", path: "tomcat.sh"
  end

  # Nginx VM configuration
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "800"
    end
    web01.vm.provision "shell", path: "nginx.sh"
  end
end
